language: java
jdk:
  - openjdk8
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn -B nondex:nondex | grep -iC 3 nondex
branches:
  except:
    - appveyor
